// <auto-generated />
using System;
using AspNetCore.Bookstore.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCore.Bookstore.Data.Migrations
{
    [DbContext(typeof(BookstoreContext))]
    [Migration("20190904132411_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCore.Bookstore.Domain.Entities.Book", b =>
                {
                    b.Property<int>("ID");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(38,2)");

                    b.Property<int>("Quantity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("ID");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Eric Evans",
                            Category = "Software",
                            CreatedDate = new DateTime(2019, 9, 4, 10, 24, 11, 537, DateTimeKind.Local).AddTicks(3478),
                            Price = 59.90m,
                            Quantity = 26,
                            Title = "Domain-Driven Design: Tackling Complexity in the Heart of Software"
                        },
                        new
                        {
                            ID = 2,
                            Author = "Robert C. Martin",
                            Category = "Software",
                            CreatedDate = new DateTime(2019, 9, 4, 10, 24, 11, 538, DateTimeKind.Local).AddTicks(7448),
                            Price = 45.90m,
                            Quantity = 13,
                            Title = "Agile Principles, Patterns, and Practices in C#"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Robert C. Martin",
                            Category = "Software",
                            CreatedDate = new DateTime(2019, 9, 4, 10, 24, 11, 538, DateTimeKind.Local).AddTicks(7475),
                            Price = 33.90m,
                            Quantity = 10,
                            Title = "Clean Code: A Handbook of Agile Software Craftsmanship"
                        },
                        new
                        {
                            ID = 4,
                            Author = "Vaughn Vernon",
                            Category = "Software",
                            CreatedDate = new DateTime(2019, 9, 4, 10, 24, 11, 538, DateTimeKind.Local).AddTicks(7478),
                            Price = 59.90m,
                            Quantity = 22,
                            Title = "Implementing Domain-Driven Design"
                        },
                        new
                        {
                            ID = 5,
                            Author = "Scott Millet",
                            Category = "Software",
                            CreatedDate = new DateTime(2019, 9, 4, 10, 24, 11, 538, DateTimeKind.Local).AddTicks(7481),
                            Price = 42.90m,
                            Quantity = 15,
                            Title = "Patterns, Principles, and Practices of Domain-Driven Design"
                        },
                        new
                        {
                            ID = 6,
                            Author = "Martin Fowler",
                            Category = "Software",
                            CreatedDate = new DateTime(2019, 9, 4, 10, 24, 11, 538, DateTimeKind.Local).AddTicks(7483),
                            Price = 31.90m,
                            Quantity = 5,
                            Title = "Refactoring: Improving the Design of Existing Code"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
